name: patrol_example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  
  patrol: ^3.7.1

flutter:

  uses-material-design: true

patrol:
  app_name: Patrol example
  android:
    package_name: com.example.patrol_example
  ios:
    bundle_id: com.example.patrolExample
